### ISSUE TITLE
I got 1 Bot working, but the second doens't want to work

### ISSUE THREAD

**Issue by SirRicharalar** [nguyenquyhy/DiscordBridge#52]
I followed each step in the read me file, worked for my first server.

I did it all over again, but it doesn't work on my second server. I noticed that the first one had a tag thats not in my roles (discord side).

**Comment by BigJazzz** [comment]
@SirRicharalar can you post your config here? Strip out access tokens and such, and I can have a look. I had the same issue, and managed to get it working.

Also, `/discord reload` doesn't work at the moment (it'll be fixed in the next update according to the dev #49 ) so if you haven't restarted your server that'd be why.
